"""app_jimmy_harter.py - Project script.

Author: Jimmy Harter
Date: 2026-01

Practice key Python skills:
- docstring comments used at the start of each module and function
- pathlib for cross-platform file paths
- creating and writing files
- type hints (explicit types)
- logging (preferred over print)
- repetition patterns:
  - for year in range(...)
  - for item in list
  - list comprehension
  - while loop
- standard Python entry point pattern (if __name__ == "__main__":)

OBS:
  This is my file to practice and customize.
  As I complete TODOs, I remove them.
  All generated files start with my name in the filename.
"""

# === DECLARE IMPORTS (BRING IN FREE CODE) ===

import logging
from pathlib import Path
import time
from typing import Final

# External (must be listed in pyproject.toml)
from datafun_toolkit.logger import get_logger, log_header

# === CONFIGURE LOGGER ONCE PER MODULE (FILE) ===

LOG: logging.Logger = get_logger("P02", level="DEBUG")

# === DECLARE SOME GLOBAL CONSTANTS ===

ROOT_DIR: Final[Path] = Path.cwd()
NAME_PREFIX: Final[str] = "jimmy_harter"

# A non-pet list used for file creation
REGIONS: Final[list[str]] = [
    "North America",
    "South America",
    "Europe",
    "Asia",
    "Africa",
    "Oceania",
    "Middle East",
]

# === HELPER FUNCTION: WRITE A FILE AND LOG IT ===


def write_text_file(path: Path, content: str) -> None:
    """Write content to a text file (overwriting if it exists)."""
    path.write_text(content, encoding="utf-8")
    LOG.info(f"WROTE file: {path.name}")


# === REPETITION FUNCTION 1: FOR EACH IN NUMERIC RANGE ===


def create_files_from_numeric_range() -> None:
    """Create a file for each year in the range 2023 to 2026 inclusive."""
    LOG.info("START FUNCTION 1: create_files_from_numeric_range()")

    start_year: int = 2023
    end_year: int = 2026

    LOG.info(f"Starting year: {start_year}")
    LOG.info(f"Ending year: {end_year}")

    for year in range(start_year, end_year + 1):
        filename: str = f"{NAME_PREFIX}_year_{year}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            f"Jimmy Harter - Annual Automation File\n"
            f"Year: {year}\n"
            f"Generated by repetition over a numeric range.\n"
        )
        write_text_file(path, content)


# === REPETITION FUNCTION 2: FOR ITEM IN LIST ===


def create_files_from_list() -> None:
    """Create a file for each region in a list."""
    LOG.info("START FUNCTION 2: create_files_from_list()")

    LOG.info(f"Regions list: {REGIONS}")

    for region in REGIONS:
        safe_region: str = region.lower().replace(" ", "_")
        filename: str = f"{NAME_PREFIX}_region_{safe_region}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            f"Jimmy Harter - Region Automation File\n"
            f"Region: {region}\n"
            f"Generated by iterating over a list.\n"
        )
        write_text_file(path, content)


# === REPETITION FUNCTION 3: USING LIST COMPREHENSION ===


def create_files_using_list_comprehension() -> None:
    """Create files using a transformed list created via list comprehension."""
    LOG.info("START FUNCTION 3: create_files_using_list_comprehension()")
    LOG.info("WHY: Transform a list into a new list using list comprehension.")

    # Transform regions into tag-style labels (e.g., "tag_europe")
    region_tags: list[str] = [f"tag_{r.lower().replace(' ', '_')}" for r in REGIONS]
    LOG.info(f"Region tags: {region_tags}")

    for tag in region_tags:
        filename: str = f"{NAME_PREFIX}_{tag}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            f"Jimmy Harter - Region Tag File\n"
            f"Tag: {tag}\n"
            f"Generated from a list comprehension transformation.\n"
        )
        write_text_file(path, content)


# === REPETITION FUNCTION 4: WHILE LOOP (PERIODIC) ===


def create_files_periodically() -> None:
    """Create a small number of files with a delay between each creation."""
    LOG.info("START FUNCTION 4: create_files_periodically()")
    LOG.info("WHY: Use while loop for repetitive tasks with a delay.")

    wait_seconds: int = 1
    count: int = 5  # must be at least 5 and less than 25

    LOG.info(f"Waiting seconds between files: {wait_seconds}")
    LOG.info(f"Number of files to create: {count}")

    i: int = 1
    while i <= count:
        filename: str = f"{NAME_PREFIX}_periodic_{i:02d}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            f"Jimmy Harter - Periodic File\n"
            f"File number: {i}\n"
            f"Created with a while loop and a delay of {wait_seconds} second(s).\n"
        )
        write_text_file(path, content)

        LOG.info(f"Waiting {wait_seconds} seconds...")
        time.sleep(wait_seconds)
        i += 1


# === MAIN FUNCTION ===


def main() -> None:
    """Entry point for the script."""
    log_header(LOG, "Automation: Creating Files with Repetition Patterns")
    LOG.info("START main()")

    create_files_from_numeric_range()
    create_files_from_list()
    create_files_using_list_comprehension()
    create_files_periodically()

    LOG.info("END main()")


# === CONDITIONAL EXECUTION GUARD ===

if __name__ == "__main__":
    main()

